name: client
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flex_color_scheme: ^4.1.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  json_patch: ^3.0.0
  rxdart: ^0.27.3
  web_socket_channel: ^2.1.0

flutter:
  uses-material-design: true
