name: sangre
description: A dataflow framework
version: 1.0.0

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  dartz: ^0.10.1
  postgres: ^2.4.3
  rxdart: ^0.27.3
  test: ^1.19.2

dev_dependencies:
  lints: ^1.0.0
