name: sangre
description: A dataflow framework
version: 1.0.0

environment:
  sdk: '>=2.14.3 <3.0.0'

scripts:
  test: docker-compose -f test/docker-compose.yml run test

dependencies:
  dartz: ^0.10.1
  json_patch: ^3.0.0
  postgres: ^2.4.3
  realtime_client: ^0.1.12+1
  rxdart: ^0.27.3

dev_dependencies:
  alfred: ^0.1.5+3
  lints: ^1.0.0
  test: ^1.19.2
