version: '3.1'

volumes:
  db-data:

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: example
    volumes: 
      - db-data:/var/lib/postgresql/data
      - ./db.init.sh:/docker-entrypoint-initdb.d/db.init.sh
    ports:
      - 5432:5432

  pgweb:
    image: sosedoff/pgweb
    ports: 
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://postgres:example@db:5432/postgres?sslmode=disable
    depends_on:
      - db
        
  realtime:
    image: supabase/realtime
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PASSWORD: example
      SECURE_CHANNELS: false
    ports:
      - 4000:4000

  test: &dart
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    depends_on:
      - db
      - realtime
    environment:
      POSTGRES_SERVER: db
      REALTIME_SERVER: realtime
    # We force serial test as they depend on the same database
    # Somehow tests work one by one but not alltogether
    command: dart test --concurrency=1
      
  example: 
    <<: *dart
    command: dart example/server.dart
    ports:
      - 3000:3000